//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nValid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nValid.Resources.DefaultMessages", typeof(DefaultMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Property} is invalid..
        /// </summary>
        internal static string nValid_Custom_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_Custom_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be equal to {0}..
        /// </summary>
        internal static string nValid_Equal_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_Equal_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be greater or equal to {0}..
        /// </summary>
        internal static string nValid_GreaterOrEqualTo_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_GreaterOrEqualTo_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be greater than {0}..
        /// </summary>
        internal static string nValid_GreaterThan_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_GreaterThan_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be between {0} and {1} characters long..
        /// </summary>
        internal static string nValid_Length_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_Length_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Property} cannot be empty..
        /// </summary>
        internal static string nValid_ListNotEmpty_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_ListNotEmpty_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be lower or equal to {0}..
        /// </summary>
        internal static string nValid_LowerOrEqualTo_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_LowerOrEqualTo_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} must be lower than {0}..
        /// </summary>
        internal static string nValid_LowerThan_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_LowerThan_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Property}} cannot be equal to {0}..
        /// </summary>
        internal static string nValid_NotEqual_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_NotEqual_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Property} must have a value..
        /// </summary>
        internal static string nValid_NotNull_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_NotNull_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Property} does not have the correct format..
        /// </summary>
        internal static string nValid_RegEx_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_RegEx_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Property} cannot be empty..
        /// </summary>
        internal static string nValid_StringNotEmpty_DefaultMessage {
            get {
                return ResourceManager.GetString("nValid_StringNotEmpty_DefaultMessage", resourceCulture);
            }
        }
    }
}
